UI-MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SC.UI.MVC.Models;

namespace SC.UI.MVC.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

UI-MVC/Controllers/TicketController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SC.BL;
using SC.BL.Domain;
using SC.UI.MVC.Models;

namespace SC.UI.MVC.Controllers
{
    [Authorize]
    public class TicketController : Controller
    {
        private ITicketManager mgr;
        private readonly UserManager<User> userManager;
        public readonly SignInManager<User> SignInManager;
        public TicketController(ITicketManager ticketManager, UserManager<User> userManager, SignInManager<User> SignInManager)
        {
            mgr = ticketManager;
            this.userManager = userManager;
            this.SignInManager = SignInManager;
        }

        // GET: /Ticket
        public IActionResult Index()
        {
            IEnumerable<Ticket> tickets = mgr.GetTickets();
            return View(tickets);
        }

        public IActionResult ShowOnlyUserTicket()
        {
            IEnumerable<Ticket> tickets = mgr.GetTicketOfUser(userManager.GetUserId(User));
            return View(tickets);
        }

        // GET: /Ticket/Details/<ticket_number>
        public IActionResult Details(int id)
        {
            Ticket ticket = mgr.GetTicket(id);

            if (ticket.Responses != null)
                ViewBag.Responses = ticket.Responses;
            else
                ViewBag.Responses = mgr.GetTicketResponses(ticket.TicketNumber);

            return View(ticket);
        }

        // GET: /Ticket/Edit/<ticket_number>
        public IActionResult Edit(int id)
        {
            Ticket ticket = mgr.GetTicket(id);
            return View(ticket);
        }

        // POST: /Ticket/Edit/<ticket_number>
        [HttpPost]
        public IActionResult Edit(int id, Ticket ticket)
        {
            if (!ModelState.IsValid)
                return View(ticket);

            mgr.ChangeTicket(ticket);
            return RedirectToAction("Details", new {id = ticket.TicketNumber});
        }

        // GET: /Ticket/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: /Ticket/Create
        [HttpPost]
        public IActionResult Create(CreateTicketViewModel createTicket)
        {
            User user = userManager.FindByNameAsync(User.Identity.Name).Result;
            Ticket newTicket = mgr.AddTicket(user, createTicket.Problem);
            return RedirectToAction("Details", new {id = newTicket.TicketNumber});
        }

        // GET: /Ticket/Delete/<ticket_number>
        public IActionResult Delete(int id)
        {
            Ticket ticket = mgr.GetTicket(id);
            return View(ticket);
        }

        // POST: /Ticket/Delete/<ticket_number>
        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            mgr.RemoveTicket(id);
            return RedirectToAction("Index");
        }
    }
}

UI-MVC/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using SC.BL.Domain
@inject SignInManager<User> SignInManager;

@{
    ViewData["Title"] = "Home Page";
}

<div class="jumbotron">
    <h1>SupportCenter</h1>
    <p>Welkom op het online helpdesk systeem.</p>
</div>

<div class="row">
    <div class="col col-md-4">
        <h2>Nieuw ticket</h2>
        <p>Maak een nieuw ticket aan in het systeem.</p>
        <a class="btn btn-light" asp-controller="Ticket" asp-action="Create">Nieuw ticket</a>
    </div>
    <div class="col col-md-4">
        <h2>Alle tickets</h2>
        <p>Toont een lijst van alle bestaande tickets.</p>
        <a class="btn btn-light" asp-controller="Ticket" asp-action="Index">Alle tickets</a>
    </div>
    <div class="col col-md-4">
        <h2>Toon ticket</h2>
        <p>Geeft de details van één ticket.</p>
        <form asp-controller="Ticket" asp-action="Details" method="get" class="form-inline">
            <input name="id" type="number" placeholder="Ticketnummer" class="form-control"/>
            <input type="submit" value="Toon ticket" class="btn btn-light"/>
        </form>
    </div>
</div>
<br/>
<br/>
<div>
    <div class="row">
        <div class="col col-md-8">
            @if (SignInManager.IsSignedIn(User))
            {
                @if (User.IsInRole("Admin"))
                {
                    <h2 class="text-danger">je bent een admin</h2>
                }
                else
                {
                    <h2 class="text-danger">je bent een gebruiker</h2>
                }
            }
            else
            {
                <h2 class="text-danger">je bent niet ingelogd</h2>
            }
        </div>
    </div>
</div>